name: Check for environment.prod.ts changes

on:
  pull_request:

jobs:
  check-changes:  # Job name can be anything descriptive
    runs-on: ubuntu-latest
    steps:         # This is the correct key for defining steps within a job
      - uses: actions/checkout@v3

      - name: Install Git
        run: sudo apt-get update && sudo apt-get install git -y

      - name: Check for changes in environment.prod.ts
        run: |
          git diff --cached --name-only | grep -q "rodins-ui/src/environments/environment.prod.ts"
          if [[ $? -eq 0 ]]; then
            echo "Error: Changes detected in environment.prod.ts"
            exit 1
          fi

      - name: Upload check results
        uses: actions/checkout@v3
        with:
          persist-credentials: false
        steps:  # This step uses another action (`actions/github-script@v6`)
          - name: Run GitHub Actions
            uses: actions/github-script@v6
            with:
              script: |
                github.issues.createComment({
                  issue_number: context.issue.number,
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  body: "**Merge blocked! Changes detected in environment.prod.ts.** Please remove these changes before merging."
                })
